### ISSUE TITLE
Sample deployment

### ISSUE THREAD

**Issue by CalamarBicefalo** [thomasdarimont/keycloak-infini-kube#2]
Since this image is intended to be run within kubernetes it would be most helpful to include a working example of a deployment.

I personally cannot get the cluster working. Sometimes it forms, sometimes it doesn't. Scaling won't add new pods within the cluster.

DB connectivity is sorted, since we are using GCP we use a SQL proxy.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: keycloak
        name: keycloak

    spec:
      # This service account has been granted appropriate permissions
      serviceAccountName: keycloak-kubeping-service-account
      volumes:
      - name: keycloak-google-credentials
        secret:
          secretName: keycloak-google-credentials

      containers:
      - env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: 127.0.0.1
        - name: DB_DATABASE
          value: deleteme
        - name: DB_USER
          value: keycloak
        - name: DB_PASSWORD
          value: <<your-password>>
        image: <<this-docker-image-in-a-registry>>:latest
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP

        resources:
          requests:
            cpu: 2
            memory: "1024Mi"
          limits:
            cpu: 2
            memory: "1024Mi"

      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=a-gcp-postgres-db=tcp:5432",
                  "-credential_file=/secrets/cloudsql/key.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: keycloak-google-credentials
            mountPath: /secrets/cloudsql
            readOnly: true


---

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
    name: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30000
  selector:
    app: keycloak
    name: keycloak

```

**Comment by CalamarBicefalo** [comment]
I am going to start answering my own question.

This deployment in minikube seems to work just fine, in case anyone needs it:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
        name: keycloak
    spec:
      serviceAccountName: keycloak-kubeping-service-account

      containers:
      - env:
        - name: ROOT_LOGLEVEL
          value: TRACE
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
#this is just the docker image from our dockerhub repo
        image: boclipsconcourse/keycloak-kubeping:original
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP

        resources:
          requests:
            cpu: 1
            memory: "1024Mi"
          limits:
            cpu: 1
            memory: "1024Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
    name: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30000
  selector:
    app: keycloak
    name: keycloak

```

Why it doesn't work in GCP remains a mystery to be resolved as of right now.
